### ISSUE TITLE
radiation Analysis for honeybee ( color doesn't come out)

### ISSUE THREAD

**Issue by wyxai224** [ladybug-analysis-tools/honeybee-grasshopper#86]
![radiation analyse](https://user-images.githubusercontent.com/38140776/38563413-6c9714e2-3ca2-11e8-8833-010a2dcfee22.png)

I don't know why it doesn't work. It actually works if the surfaces are made in dynamo.

**Comment by mostaphaRoudsari** [comment]
Hi @wyxai224, this is most likely because all the values from your analysis are the same. Can you check the values? I thought I fixed it recently. Which version of Honeybee package are you using?

**Comment by wyxai224** [comment]
![value 1](https://user-images.githubusercontent.com/38140776/38682187-186a64fc-3e30-11e8-8a9a-1f560be19613.PNG)
Hi@mostaphaRoudsari , I used the 0.17 Honeybee which I think it's the latest version. And why the solar value turned into the 0 after "solar radiation analysis" node?

**Comment by mostaphaRoudsari** [comment]
Hi @wyxai224, these components are old Ladybug component and not Honeybee. Please use the updated sample file that comes with the Honeybee package.

**Comment by wyxai224** [comment]
![radiation analyse 2](https://user-images.githubusercontent.com/38140776/38705367-f30d18aa-3e6e-11e8-8552-64a1314b7f7a.png)
@mostaphaRoudsari  I used the latest sample in Honeybee package.  And I install the RADIANCE, while it still doesn't work..... The error is " 'stackvalue' object has no attribute ' parse_blind_states' ".

**Comment by mostaphaRoudsari** [comment]
I'm closing this issue! Please re-post it to the forum if the issue is not solved: discourse.ladybug.tools
